modLoader="javafml"
loaderVersion="${loader_version_range}"
license="BSD 3-Clause"

[[mods]]
modId="kaleidoscopecookery_automation"
version="1.0.0"
displayName="KaleidoscopeCookery:Automation"
authors="摸里傻"

description='''
一个为森罗厨房引入浪漫而不失沉浸感的自动化方式的mod
'''

[[mixins]]
config="kaleidoscopecookery_automation.mixins.json"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[dependencies."kaleidoscopecookery_automation"]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies."kaleidoscopecookery_automation"]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies."kaleidoscopecookery_automation"]]
    modId="kaleidoscope_cookery"
    type="required"
    versionRange="[1.2.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies."kaleidoscopecookery_automation"]]
    modId="create"
    type="required"
    versionRange="[6.0.8,)"
    ordering="NONE"
    side="BOTH"
